apiVersion: v1
kind: Secret
metadata:
  name: shopcloud-app-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://replace-user:replace-password@replace-host:5432/shopcloud_orders"
  INVOICE_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/replace-account/shopcloud-dev-invoice-queue"
  INVOICE_DLQ_URL: "https://sqs.us-east-1.amazonaws.com/replace-account/shopcloud-dev-invoice-queue-dlq"
  INVOICE_BUCKET_NAME: "shopcloud-dev-invoices-680666325893"
  SES_FROM_EMAIL: "noreply@shopcloud-dev.example.com"
  COGNITO_USER_POOL_ID: "REPLACE_WITH_CUSTOMER_POOL_ID"
  COGNITO_CLIENT_ID: "REPLACE_WITH_CUSTOMER_CLIENT_ID"
  COGNITO_ADMIN_GROUP: "admins"
