apiVersion: v1
kind: Secret
metadata:
  name: shopcloud-app-secrets
type: Opaque
stringData:
  POSTGRES_USER: "shopcloud"
  POSTGRES_PASSWORD: "change-me-postgres"
  POSTGRES_DB: "shopcloud_orders"
  INVOICE_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/680666325893/shopcloud-dev-invoice-queue"
  INVOICE_DLQ_URL: "https://sqs.us-east-1.amazonaws.com/680666325893/shopcloud-dev-invoice-queue-dlq"
  INVOICE_BUCKET_NAME: "shopcloud-dev-invoices-680666325893"
  SES_FROM_EMAIL: "noreply@shopcloud-dev.example.com"
