apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 680666325893.dkr.ecr.us-east-1.amazonaws.com/shopcloud-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          env:
            - name: PORT
              value: "3005"
            - name: AWS_REGION
              value: "us-east-1"
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_ADMIN_GROUP
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: COGNITO_ADMIN_GROUP
            - name: ENABLE_LOCAL_AUTH
              value: "false"
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
