apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth-sa
      containers:
        - name: auth
          image: 680666325893.dkr.ecr.us-east-1.amazonaws.com/shopcloud-auth:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          env:
            - name: PORT
              value: "3005"
            - name: AWS_REGION
              value: "us-east-1"
            - name: USE_AWS_SSM_AUTH_CONFIG
              value: "false"
            - name: AUTH_SSM_CUSTOMERS_POOL_ID_PARAM
              value: "/shopcloud/dev/auth/cognito/customers_pool_id"
            - name: AUTH_SSM_CUSTOMERS_CLIENT_ID_PARAM
              value: "/shopcloud/dev/auth/cognito/customers_client_id"
            - name: AUTH_SSM_ADMINS_POOL_ID_PARAM
              value: "/shopcloud/dev/auth/cognito/admins_pool_id"
            - name: AUTH_SSM_ADMINS_CLIENT_ID_PARAM
              value: "/shopcloud/dev/auth/cognito/admins_client_id"
            - name: AUTH_SSM_ADMIN_GROUP_PARAM
              value: "/shopcloud/dev/auth/cognito/admin_group"
            - name: COGNITO_ADMIN_GROUP
              value: "admins"
            - name: COGNITO_CUSTOMERS_USER_POOL_ID
              value: "us-east-1_KSzEFHldo"
            - name: COGNITO_CUSTOMERS_CLIENT_ID
              value: "60h40p5v95h1iqirci2s4i3qfl"
            - name: COGNITO_ADMINS_USER_POOL_ID
              value: "us-east-1_X58zLGhXN"
            - name: COGNITO_ADMINS_CLIENT_ID
              value: "2k65o70is0hu4ekjcki5at84tg"
            - name: ENABLE_LOCAL_AUTH
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
