apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      serviceAccountName: checkout-sa
      containers:
        - name: checkout
          image: 680666325893.dkr.ecr.us-east-1.amazonaws.com/shopcloud-checkout:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: AWS_REGION
              value: "us-east-1"
            - name: USE_AWS_SECRETS
              value: "true"
            - name: CHECKOUT_CONFIG_SECRET_ID
              value: "shopcloud/dev/checkout"
            - name: INVOICE_MODE
              value: "sqs"
            - name: CART_SERVICE_URL
              value: "http://cart:3002"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog:3001"
            - name: INVOICE_WORKER_URL
              value: "http://invoice-worker:3004"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 20
