apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-worker
  labels:
    app: invoice-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: invoice-worker
  template:
    metadata:
      labels:
        app: invoice-worker
    spec:
      containers:
        - name: invoice-worker
          image: 680666325893.dkr.ecr.us-east-1.amazonaws.com/shopcloud-invoice-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: AWS_REGION
              value: "us-east-1"
            - name: INVOICE_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/680666325893/shopcloud-dev-invoice-queue"
            - name: INVOICE_DLQ_URL
              value: "https://sqs.us-east-1.amazonaws.com/680666325893/shopcloud-dev-invoice-queue-dlq"
            - name: INVOICE_BUCKET_NAME
              value: "shopcloud-dev-invoices-680666325893"
            - name: SES_FROM_EMAIL
              value: "noreply@shopcloud-dev.example.com"
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 20
