apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-worker
  labels:
    app: invoice-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: invoice-worker
  template:
    metadata:
      labels:
        app: invoice-worker
    spec:
      serviceAccountName: invoice-worker-sa
      containers:
        - name: invoice-worker
          image: 680666325893.dkr.ecr.us-east-1.amazonaws.com/shopcloud-invoice-worker:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: AWS_REGION
              value: "us-east-1"
            - name: INVOICE_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: INVOICE_QUEUE_URL
            - name: INVOICE_DLQ_URL
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: INVOICE_DLQ_URL
            - name: INVOICE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: INVOICE_BUCKET_NAME
            - name: SES_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: shopcloud-app-secrets
                  key: SES_FROM_EMAIL
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 20
