server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/products {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://catalog:3001/products;
  }

  location /api/cart/ {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://cart:3002/cart/;
  }

  location /api/checkout {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://checkout:3003/checkout;
  }

  location /api/login {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://auth:3005/auth/login;
  }

  location /api/register {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://auth:3005/auth/register;
  }

  location /api/orders {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://checkout:3003/orders;
  }

  location /api/auth/me {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://auth:3005/auth/me;
  }

  location /api/auth/admin-check {
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://auth:3005/auth/admin-check;
  }

  location /health {
    add_header Content-Type application/json;
    return 200 '{"service":"nginx-frontend","status":"ok"}';
  }
}
